
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  server:
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 5
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
